#!/usr/bin/env python3
"""
Script to generate all_symbols.txt from PyLiPD and Pyleoclim documentation.

Usage:
    python scripts/generate_symbols.py <docs_path> [output_file]

Example:
    python scripts/generate_symbols.py my_docs_simple/pylipd/docs
    python scripts/generate_symbols.py my_docs_simple/pyleoclim/docs backend/all_symbols.txt
"""

import sys
import pathlib
import subprocess
import argparse

def main():
    parser = argparse.ArgumentParser(description="Generate all_symbols.txt from documentation")
    parser.add_argument("docs_path", help="Path to documentation directory")
    parser.add_argument("output_file", nargs="?", default="backend/all_symbols.txt", 
                       help="Output file path (default: backend/all_symbols.txt)")
    args = parser.parse_args()
    
    docs_path = pathlib.Path(args.docs_path)
    output_file = pathlib.Path(args.output_file)
    
    if not docs_path.exists():
        print(f"Error: Documentation path {docs_path} does not exist")
        sys.exit(1)
    
    # Ensure output directory exists
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    print(f"Generating symbols from {docs_path} to {output_file}")
    
    try:
        # Run the show_all_symbols script and capture output
        cmd = [sys.executable, "-m", "libraries.readthedocs_library.show_all_symbols", str(docs_path)]
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=pathlib.Path(__file__).parent.parent)
        
        if result.returncode != 0:
            print(f"Error running show_all_symbols: {result.stderr}")
            sys.exit(1)
        
        # Write output to file
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("# PyLiPD and Pyleoclim Function Signatures\n")
            f.write(f"# Generated from: {docs_path}\n")
            f.write("# Generated by: python -m libraries.readthedocs_library.show_all_symbols\n\n")
            f.write(result.stdout)
        
        print(f"✅ Successfully generated {output_file}")
        print(f"📊 Generated {len(result.stdout.splitlines())} function signatures")
        
    except Exception as e:
        print(f"❌ Error generating symbols: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main() 