---
title: "Getting Started"
sidebar: getting-started
---

This section provides instructions for installing and using PaleoPAL, as well as guides for advanced users and developers.

## Installation

If you are new to PaleoPAL, we recommend starting with the [Docker installation guide](docker.qmd). This guide provides step-by-step instructions for installing PaleoPAL and indexing the libraries that power it. We also provide a [VS Code extension](vscode-extension.qmd) that allows you to use PaleoPAL directly in your Jupyter Notebooks. 

If you are an advanced user or developer, you can follow the [local development setup guide](local-setup.qmd) to install PaleoPAL locally and customize it to your needs.

If you need to update the libraries that power PaleoPAL, you can follow the [updating libraries guide](updating-libraries.qmd) to keep your local installation up to date.

You can access all these guides from the sidebar or by clicking on the links below:

| | |
|---|---|
| [Installing PaleoPAL with Docker](docker.qmd) | Installs PaleoPAL and index the libraries|
| [VS Code Extension](vscode-extension.qmd) | Install the VS Code extension |
| [Updating Libraries](updating-libraries.qmd) | Instructions for keeping the knowledge base libraries up to date |
| [Advanced Installation](local-setup.qmd) | Instructions for local development and custom setups (not recommended for most users) |

## Using PaleoPAL

There are two main ways to interact with PaleoPAL: through the frontend interface or through the VS Code extension. The frontend interface allows you to interact with PaleoPAL through a web browser, while the VS Code extension allows you to use PaleoPAL directly in your Jupyter Notebooks.

::: {.callout-important}
Your data (data and code) stay on your computer. PaleoPAL does not send your data to any external servers. The only data that is sent to external servers are the queries you send to the LLMs (e.g., OpenAI, Anthropic, Google, Ollama, Grok). You can also use a local LLM (e.g., Ollama, Grok) to avoid sending any data to external servers.
:::

| | |
|---|---|
| [Using PaleoPAL through the web interface](using-paleopal-web.qmd) | Instructions on using PaleoPAL in a web browser|
| [Using PaleoPAL through the VS Code extension](using-paleopal-vscode.qmd) | Instructions on using PaleoPAL in the VS Code extension |
