from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field

class ExecutionResult(BaseModel):
    """Unified execution result structure for all agents."""
    type: str = Field(..., description="'execution_success' or 'execution_error'")
    output: str = Field(default="", description="stdout/stderr text from execution")
    execution_time: float = Field(default=0.0, description="Execution time in seconds")
    variable_summary: Optional[Dict[str, Any]] = Field(None, description="Summary of variables created")
    plots: List[str] = Field(default_factory=list, description="Paths to generated plot files")
    error: Optional[str] = Field(None, description="Error message if execution failed")

class Message(BaseModel):
    """Represents a single chat message with unified metadata across all agents."""
    id: str = Field(..., description="Unique message ID")
    conversation_id: str = Field(..., description="ID of the parent conversation")
    sequence_number: int = Field(..., description="Message order within conversation")
    
    # Core message content
    role: str = Field(..., description="Role of the sender: 'user' or 'assistant'")
    content: str = Field(..., description="Message content")
    
    # Message classification
    message_type: str = Field(default="chat", description="Type: 'chat', 'clarification', 'system', 'progress'")
    agent_type: Optional[str] = Field(None, description="Which agent generated this message (for assistant messages)")
    
    # Generation results (unified across all agents)
    generated_code: Optional[str] = Field(None, description="Python code generated by any agent")
    
    # Execution results (unified structure for all agents)
    execution_results: Optional[List[ExecutionResult]] = Field(None, description="Structured execution results")
    
    # Variable tracking (unified)
    result_variable_names: Optional[List[str]] = Field(None, description="Names of variables created during execution")
    
    # Agent-specific metadata (unified field for all agent-specific data)
    agent_metadata: Optional[Dict[str, Any]] = Field(None, description="Agent-specific metadata (SPARQL queries, workflow plans, etc.)")
    
    # Search and context results
    similar_results: Optional[List[Any]] = Field(None, description="Similar queries/code found during search")
    entity_matches: Optional[List[Any]] = Field(None, description="Entity matches from search")
    
    # Clarification state
    needs_clarification: bool = Field(default=False, description="Whether this message needs clarification")
    clarification_questions: Optional[List[Any]] = Field(None, description="Clarification questions for this message")
    clarification_responses: Optional[List[Dict[str, Any]]] = Field(None, description="Structured clarification responses")
    
    # UI display flags (derived from data above, but stored for performance)
    has_execution_results: bool = Field(default=False, description="Whether message has execution results")
    has_generated_code: bool = Field(default=False, description="Whether message has generated code")
    has_error: bool = Field(default=False, description="Whether message represents an error")
    
    # Progress tracking
    is_node_progress: bool = Field(default=False, description="Whether this is a progress update message")
    owner_message_id: Optional[str] = Field(None, description="For progress messages, which user message triggered this")
    phase: Optional[str] = Field(None, description="Progress phase: 'start', 'complete'")
    node_name: Optional[str] = Field(None, description="Name of the processing node")
    
    # Timestamps
    created_at: str = Field(..., description="Creation timestamp (ISO)")
    updated_at: str = Field(..., description="Last update timestamp (ISO)")
    
    # Additional metadata (for extensibility)
    metadata: Optional[Dict[str, Any]] = Field(None, description="Additional message metadata")

    class Config:
        extra = "allow"
        validate_by_name = True
        from_attributes = True

class MessageCreate(BaseModel):
    """Schema for creating a new message."""
    conversation_id: str
    role: str
    content: str
    message_type: str = "chat"
    agent_type: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None

class MessageUpdate(BaseModel):
    """Schema for updating message results and metadata."""
    generated_code: Optional[str] = None
    execution_results: Optional[List[ExecutionResult]] = None
    result_variable_names: Optional[List[str]] = None
    agent_metadata: Optional[Dict[str, Any]] = None
    similar_results: Optional[List[Any]] = None
    entity_matches: Optional[List[Any]] = None
    needs_clarification: Optional[bool] = None
    clarification_questions: Optional[List[Any]] = None
    clarification_responses: Optional[List[Dict[str, Any]]] = None
    metadata: Optional[Dict[str, Any]] = None 